### ISSUE TITLE
Android Camera

### ISSUE THREAD

**Issue by Jitesh291x** [devkenante/KenanteJanusIssuetracker#2]
Two errors seen on Android ->
1. Camera freezes and stops sending camera stream to server (during call)
2. Camera closes when app is in background for too long.

**Comment by Jitesh291x** [comment]
Logs for camera freeze error 
[camera freeze error.txt](https://github.com/devkenante/KenanteJanusIssuetracker/files/3978074/camera.freeze.error.txt)

**Comment by devkenante** [comment]
Resolved in Klite 1.00 version
